name: postalhub_admin_cms
description: "Postalhub CMS"

publish_to: 'none' 

version: 24.5.30+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.7.0
  animations: ^2.0.8
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7
  path: ^1.9.0
  firebase_core: ^2.31.0
  firebase_storage: ^11.6.0
  firebase_database: ^10.5.5
  firebase_auth: ^4.20.0
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+4
  visibility_detector: ^0.2.0
  shimmer: ^2.0.0
  file_picker: ^8.0.3
  another_stepper: ^1.2.2
  image_picker_for_web: ^3.0.5
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.0
  barcode_scan2: ^4.3.3
  permission_handler: ^11.3.1
  image_picker_web: ^4.0.0
  firebase_messaging: ^14.9.4
  ##camera: ^0.11.0+2
  ##image_compression_flutter: ^1.0.4
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/postalhub_logo.jpg
  - assets/gif/not_found.gif
  - assets/gif/search.gif
